kind: pipeline
name: default

steps:
  - name: test
    image: rust:1.63
    commands:
      - cargo build --verbose --all
      - cargo test --verbose --all
      - cargo run --verbose --all-features
